version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: test-circle-ci
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_VERSION: 4.3.0
          MULE_APP_NAME: mulesoft-circle-ci-cd
          MULE_ENV: SANDBOX
          MULE_WORKER_TYP: MICRO
          MULE_WORKER: 1
    steps:
      - checkout
      - restore_cache:
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - save_cache:
          paths:
            - ~/.m2
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - run:
          name: Build
          command: |
            mvn clean -s settings.xml compile
      - run:
          name: cloudhub deployment
          command: |
            mvn clean -s settings.xml deploy -DmuleDeploy -DMULE_ENV=${MULE_ENV} -Danypoint.workers=${MULE_WORKER_TYP} -DMULE_WORKER=${MULE_WORKER} -Danypoint.username=${anypoint.username} -Danypoint.password={anypoint.password} -Danypoint.buisnessGroup=${anypoint.businessGroup} 